apiVersion: v1
kind: Service
metadata:
  name: {{ include "ttrss-helm.ttrss.fullname" . }}
  labels:
    {{- include "ttrss-helm.ttrss.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ttrss.service.serviceType }}
  {{- with .Values.ttrss.service.externalIPs }}
  externalIPs:
  {{ toYaml . | indent 2 | trim }}
  {{- end }}
  ports:
  - name: ttrss
    port: {{ .Values.ttrss.service.port }}
    targetPort: ttrss
    {{- if  .Values.ttrss.service.nodePort }}
    nodePort: {{ .Values.ttrss.service.nodePort }}
    {{- end }}
  selector:
    {{- include "ttrss-helm.ttrss.selectorLabels" . | nindent 4 }}
