apiVersion: v1
kind: Service
metadata:
  name: {{ include "ttrss-helm.nginx.fullname" . }}
  labels:
    {{- include "ttrss-helm.nginx.labels" . | nindent 4 }}
spec:
  type: {{ .Values.nginx.service.serviceType }}
  {{- with .Values.nginx.service.externalIPs }}
  externalIPs:
  {{ toYaml . | indent 2 | trim }}
  {{- end }}
  ports:
  - name: nginx
    port: {{ .Values.nginx.service.port }}
    targetPort: http
    {{- if  .Values.nginx.service.nodePort }}
    nodePort: {{ .Values.nginx.service.nodePort }}
    {{- end }}
  selector:
    {{- include "ttrss-helm.nginx.selectorLabels" . | nindent 4 }}
