apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ttrss-helm.pgsql.fullname" . }}
  labels:
    {{- include "ttrss-helm.pgsql.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ required "A valid .Values.config.dbPass entry required!" .Values.config.dbPass | b64enc }}
  POSTGRES_USER: {{ required "A valid .Values.config.dbUser entry required!" .Values.config.dbUser | b64enc }}
  POSTGRES_DB: {{ required "A valid .Values.config.dbName entry required!" .Values.config.dbName | b64enc }}
  {{- if .Values.config.pgsql.extraEnvs }}
  {{- range $key, $value := .Values.config.pgsql.extraEnvs }}
  {{- if not (kindIs "invalid" $value) }}
  {{ $key }}: {{ tpl $value $ | b64enc }}
  {{- end }}
  {{- end }}
  {{- end }}
