apiVersion: v1
kind: Service
metadata:
  name: {{ include "ttrss-helm.pgsql.fullname" . }}
  labels:
    {{- include "ttrss-helm.pgsql.labels" . | nindent 4 }}
spec:
  type: {{ .Values.pgsql.service.serviceType }}
  {{- with .Values.pgsql.service.externalIPs }}
  externalIPs:
  {{ toYaml . | indent 2 | trim }}
  {{- end }}
  ports:
  - name: pgsql
    port: {{ .Values.pgsql.service.port }}
    targetPort: pgsql
    {{- if  .Values.pgsql.service.nodePort }}
    nodePort: {{ .Values.pgsql.service.nodePort }}
    {{- end }}
  selector:
    {{- include "ttrss-helm.pgsql.selectorLabels" . | nindent 4 }}
